### PR TITLE
Find a child with path notation and print child path(s)

### PR DESCRIPTION
**Pull request by ThomasKroes**
This PR addresses the following issues:
- [x] Moves some functions for action hierarchy queries from the `DataHierarchyItem` class back to the `WidgetAction` class
- [x] Add member function to find a child action by path: `WidgetAction::findChildBypath(const QString& path)`
- [x] Add function to print children in `WidgetAction` class
- [x] Fix the missing right-click menu in `WidgetActionLabel` class
- [x] Change ManiVault version (CMake) to `1.0.0 rc`

### CODE REVIEW

**Review by JulianThijssen — APPROVED** [review]

**Comment by JulianThijssen** [comment]
Thanks for the addition! Got to really test it well last evening and everything works nicely.
One thing that caused a small bit of confusion and for which I needed to check the source code is that calling printChildren on the plugin prints the paths with the name of the plugin in front, but requesting a child by path from a plugin should be done without the name of the plugin. Maybe some documentation could make this clearer.

**Comment by ThomasKroes** [comment]
Thanks for testing! I agree with you, this is confusing. Perhaps we could omit the root name from the `printChildren(...)` function? As we know what the name is already :)

**Comment by JulianThijssen** [comment]
Yes I think that would be good :)

**Comment by ThomasKroes** [comment]
I will update it, thanks for the feedback!

**Comment by ThomasKroes** [comment]
Fixed now on the master!

**Pull request merged**
