### PR TITLE
Add Images::getScalarData(std::uint32_t imageIndex, ...) overload for retrieving image scalar data in one operation

### PR DESCRIPTION
**Pull request by ThomasKroes**

### CODE REVIEW

**Review by bldrvnlw — CHANGES_REQUESTED** [review]
getScalarData is overloaded with a vector of dimensionIndices which can be used to retrieve all the colour components which is not done in the original getScalarData . However this function name and signature (and the documentation) doesn't really make it clear that colour components. Or maybe I'm missing something...

Should the name of the comments be changed? I'm open to being convinced otherwise.

**Comment by ThomasKroes** [comment]
> However this function name and signature (and the documentation) doesn't really make it clear that colour components. 
What do you mean?

Did you notice the addition of `void Images::getImageScalarData(...)`?

**Comment by bldrvnlw** [comment]
Yes I noticed void Images::getImageScalarData(...) and it uses this new getScalarData  overload. I'm happy with that function.

But my comment is about the getScalarData overload itself. That does something that I think is radically different from the original version because of the way image components are handled. In my opinion this isn't clear because it is an overload so the name is the same and there is no mention of special component handling in the comments.  

But am I either over-complicating or misinterpreting things?

**Review by bldrvnlw — APPROVED** [review]
Image retrieval tested with JupyterPlugin

**Pull request merged**
